version: '3'

services:
  db:
    image: postgres

  web:
    build: .
    command: bash -c " python quora/manage.py collectstatic --noinput  && python quora/manage.py migrate && python quora/manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - web-variables.env
    environment:
      - DEBUG=
      - SECRET_KEY=

